export const UIActionTypes = {
  SUBMITTING_POST: 'SUBMITTING_POST',
  SUBMITTING_POST_SUCCESS: 'SUBMITTING_POST_SUCCESS',
  DELETING_POST: 'DELETING_POST',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
}